### ISSUE TITLE
Missing Files (predicate_list.txt, extra_predicates_list.txt)

### ISSUE THREAD

**Issue by KanghoonYoon** [Yuqifan1117/CaCao#13]
Thank you for sharing your work. 

I want to run the fine_grained_predicate_tuning.py, but cannot find the above files. How can I obtain these files?

**Comment by Yuqifan1117** [comment]
We have uploaded the final predicates file now in the position at 'datasets/vg'.

**Comment by KanghoonYoon** [comment]
I really appreciate your early responses!
