### ISSUE TITLE
some questions about EPIC

### ISSUE THREAD

**Issue by ENDGU** [Yuqifan1117/CaCao#18]
Hello, sorry to bother you again.I am very interested in the EPIC module section of your paper and have been trying to reproduce it recently.But I encountered some difficulties.In the image input section, you used three images in the Figure 3, representing union region, sub, and obj. May I ask: 
1: Should the corresponding images be pre cut or how to obtain them? 
2: Assuming the image has been cropped, is the CLIP model used to process the three images and then cat them as embeddings or simply add them together?

**Comment by Yuqifan1117** [comment]
1. we used the coordinates from the corresponding proposals and cropped the subject region as well as the object region for the next steps (We employ union regions for illustration purposes. In fact, we instead utilize a union feature of two corresponding regions considering the time complexity.)
2. We resize the two cropped images and input them into the CLIP model. After obtaining the image features, we add them together as the final image features to learn the predicate representation.

**Comment by ENDGU** [comment]
Thank you very much for your patient reply, which has helped me a lot!

**Comment by ENDGU** [comment]
Regarding the aspect of text processing, your Figure 3 mentions that text input has a [CLS] and [MASK] special flag, which does not seem to be included in the CLIP model's text processing. Are you using the BERT model's tokenizer to embed text?

**Comment by Yuqifan1117** [comment]
'[CLS] a photo of human [MASK] computer' represents the template triplet.  To learn the predicate representation, here we use [MASK] special flag to represent unseen predicates, which should be replaced with the corresponding text.  [CLS] represents the CLIP model’s pooled outputs and doesn't need input. So an example input would be 'a photo of human manipulation computer'.

**Comment by ENDGU** [comment]
The following text mentions that the predicate uses a Glove vector for embedding. Does it mean that in the input sentence, only the predicate uses a Glove vector or is it the entire sentence?

**Comment by Yuqifan1117** [comment]
It seems to use a clip tokenizer for the embedding. （Is that you're asking）

**Comment by ENDGU** [comment]
<img width="407" alt="image" src="https://github.com/Yuqifan1117/CaCao/assets/115676290/b999727a-f891-48ce-92c0-aa740eaf7083">

My confusion is how the Glove vector mentioned here is used.This paragraph comes from Appendix F of the paper.

**Comment by Yuqifan1117** [comment]
We have already updated several confusing mentions in the newest version (v2 in Aug).
![image](https://github.com/Yuqifan1117/CaCao/assets/48062034/50d9d557-a698-473a-a0ce-433ac0aaee01)

**Comment by ENDGU** [comment]
Thank you very much!!!!!

**Comment by ENDGU** [comment]
<img width="380" alt="image" src="https://github.com/Yuqifan1117/CaCao/assets/115676290/1d0f4c16-cdac-4e7e-9204-b4a5a4fbfcd9">

The CLIP model text embedding vector that I previously learned about seems to be [batch_size,77,512], and the image embedding is [batch_size,50,512]? What do the lengths 4 and 2 in the picture mean?

**Comment by Yuqifan1117** [comment]
The embedding is shaped as [batch_size, seq_length, embedding_size], where the lengths 4 and 2 are incorporated into the seq_length dimension.

**Comment by ENDGU** [comment]
Thank you, I'll try again.
