### ISSUE TITLE
what is the vg+cacao?

### ISSUE THREAD

**Issue by ZHUXUHAN** [Yuqifan1117/CaCao#2]
Hi, what is the VG+Cacao in table.3, others is Cacao, what is VG+cacao?

**Comment by Yuqifan1117** [comment]
Thanks! VG+CaCao represents the enhanced dataset with our CaCao framework (the base VG dataset and extra enhanced fine-grained data), while CaCao means only use CaCao’s predicates. In table.3, we use VG+CaCao distinguish it from Cacao alone.

**Comment by ZHUXUHAN** [comment]
> Thanks! VG+CaCao represents the enhanced dataset with our CaCao framework (the base VG dataset and extra enhanced fine-grained data), while CaCao means only use CaCao’s predicates. In table.3, we use VG+CaCao distinguish it from Cacao alone.

Thank you for your response. So, is this VG+Cacao referring to the file named 'VG-SGG-base-EXPANDED-with-attri.h5' in your Google drive?

**Comment by Yuqifan1117** [comment]
> > Thanks! VG+CaCao represents the enhanced dataset with our CaCao framework (the base VG dataset and extra enhanced fine-grained data), while CaCao means only use CaCao’s predicates. In table.3, we use VG+CaCao distinguish it from Cacao alone.
> 
> Thank you for your response. So, is this VG+Cacao referring to the file named 'VG-SGG-base-EXPANDED-with-attri.h5' in your Google drive?

Actually, we consider more categories of predicates in open-world here (i.e. 'VG-SGG-zs-random-expanded-with-attri.h5' in the 'vg/open-world' folder), while 'VG-SGG-base-EXPANDED-with-attri.h5' has been mapped to target 50 predicates for VG dataset.

**Comment by ZHUXUHAN** [comment]
> > > Thanks! VG+CaCao represents the enhanced dataset with our CaCao framework (the base VG dataset and extra enhanced fine-grained data), while CaCao means only use CaCao’s predicates. In table.3, we use VG+CaCao distinguish it from Cacao alone.
> > 
> > 
> > Thank you for your response. So, is this VG+Cacao referring to the file named 'VG-SGG-base-EXPANDED-with-attri.h5' in your Google drive?
> 
> Actually, we consider more categories of predicates in open-world here (i.e. 'VG-SGG-zs-random-expanded-with-attri.h5' in the 'vg/open-world' folder), while 'VG-SGG-base-EXPANDED-with-attri.h5' has been mapped to target 50 predicates for VG dataset.

so VG+Cacao is 'VG-SGG-zs-random-expanded-with-attri.h5' in the 'vg/open-world' folder?

**Comment by Yuqifan1117** [comment]
> > > > Thanks! VG+CaCao represents the enhanced dataset with our CaCao framework (the base VG dataset and extra enhanced fine-grained data), while CaCao means only use CaCao’s predicates. In table.3, we use VG+CaCao distinguish it from Cacao alone.
> > > 
> > > 
> > > Thank you for your response. So, is this VG+Cacao referring to the file named 'VG-SGG-base-EXPANDED-with-attri.h5' in your Google drive?
> > 
> > 
> > Actually, we consider more categories of predicates in open-world here (i.e. 'VG-SGG-zs-random-expanded-with-attri.h5' in the 'vg/open-world' folder), while 'VG-SGG-base-EXPANDED-with-attri.h5' has been mapped to target 50 predicates for VG dataset.
> 
> so VG+Cacao is 'VG-SGG-zs-random-expanded-with-attri.h5' in the 'vg/open-world' folder?

yes

**Comment by ZHUXUHAN** [comment]
> > > > > Thanks! VG+CaCao represents the enhanced dataset with our CaCao framework (the base VG dataset and extra enhanced fine-grained data), while CaCao means only use CaCao’s predicates. In table.3, we use VG+CaCao distinguish it from Cacao alone.
> > > > 
> > > > 
> > > > Thank you for your response. So, is this VG+Cacao referring to the file named 'VG-SGG-base-EXPANDED-with-attri.h5' in your Google drive?
> > > 
> > > 
> > > Actually, we consider more categories of predicates in open-world here (i.e. 'VG-SGG-zs-random-expanded-with-attri.h5' in the 'vg/open-world' folder), while 'VG-SGG-base-EXPANDED-with-attri.h5' has been mapped to target 50 predicates for VG dataset.
> > 
> > 
> > so VG+Cacao is 'VG-SGG-zs-random-expanded-with-attri.h5' in the 'vg/open-world' folder?
> 
> yes

ok, thanks for your help.
