### ISSUE TITLE
Can you provide how base predicates and novel predicates are splited in Open-World Predicate SGG?

### ISSUE THREAD

**Issue by Leon022** [Yuqifan1117/CaCao#20]
Hey, can you explain how base predicates and novel predicates are separated in Open-World Predicate SGG? Also, just wondering, when we're predicting with novel predicates, were their related subjects and objects actually seen during training or not?

**Comment by Yuqifan1117** [comment]
![af88a86781911cd4ff55fbca8189a762](https://github.com/Yuqifan1117/CaCao/assets/48062034/4857008c-3582-4c84-914f-f236f03046d5)
We do not restrict objects during training, but we filter the images which contain novel predicates.

**Comment by Leon022** [comment]
Thank you for your response, which has resolved my confusion.
