### ISSUE TITLE
File not found issue

### ISSUE THREAD

**Issue by fwj123-lr** [Yuqifan1117/CaCao#21]
May I ask if I need to download the file vg/1000/vg dicts.json myself, and if there is a download link.

**Comment by Yuqifan1117** [comment]
This is a sub-dataset for verifying CaCao performance (not necessary, just using Visual Genome is enough). If you need this, you can refer to ([VG-1000](https://github.com/waxnkw/IETrans-SGG.pytorch/blob/master/DATASET.md): [GoogleDrive](https://drive.google.com/file/d/1amdwuPcxZuXVU4W40FhzBi-AL1vbdCMJ/view?usp=sharing)), which is proposed by IETrans-SGG (Zhang et al.).

**Comment by fwj123-lr** [comment]
Thank you for your answer. I have another question, which is what these files are. Are they included in the VG dataset
![1](https://github.com/Yuqifan1117/CaCao/assets/67003767/2e9d8ee1-9c23-4f65-bd61-5fc33a44e63f)

**Comment by Yuqifan1117** [comment]
Most of the files are in the VG dataset, you can refer to #[issue 9](https://github.com/Yuqifan1117/CaCao/issues/9).

**Comment by fwj123-lr** [comment]
Okay, thank you very much
