### ISSUE TITLE
File Missing!

### ISSUE THREAD

**Issue by wgada** [Yuqifan1117/CaCao#23]
Hello! I can't find the file: /home/qifan/datasets/GQA/GQA_200_ID_Info.json. Where can I download GQA200 dataset? I'm looking forward to your reply! Please help me, thank you!  Best wishes for you!

**Comment by Yuqifan1117** [comment]
Hi! We follow the same preprocessing with [SHA-GCL-for-SGG](https://github.com/dongxingning/SHA-GCL-for-SGG). Please download the GQA file from [GQA_200_ID_Info.json](https://drive.google.com/file/d/1eDZfLqV5sPteIWLxb432HwlMTXmeq4CI/view) (by [LLM4SGG](https://github.com/rlqja1107/torch-LLM4SGG) Kim et al.)
