### ISSUE TITLE
How to train openworld?

### ISSUE THREAD

**Issue by ZHUXUHAN** [Yuqifan1117/CaCao#5]
I just use the openword/files to train the baseline motifs model, and just test the model (588 classes) with evulating the base and novel classes' Recall, is it right?

**Comment by Yuqifan1117** [comment]
yes, it seems right, however, you should predict novel classes by unified embedding mapping (Open-World Predicate SGG Backbone).

**Comment by ZHUXUHAN** [comment]
i don't understand what is the unified embedding mapping? if i train the model as what i say, is the output embedding of the model is the ''unified embedding mapping'?

**Comment by Yuqifan1117** [comment]
yes

**Comment by ZHUXUHAN** [comment]
> yes

ok, thanks for your answer.
