### ISSUE TITLE
All attribute are 0

### ISSUE THREAD

**Issue by zhangjingxian1998** [Yuqifan1117/CaCao#6]
Hi, I downloaded the VG-SGG-base-EXPANDED-dicts-with-attri.json and found the attributes are all set to 0. Are the attribute useless?
![image](https://github.com/Yuqifan1117/CaCao/assets/81813465/2507df5a-374b-4cf0-a0c1-d2637178d2cb)

**Comment by Yuqifan1117** [comment]
Thank you for your attention! In our tasks and methods, we address the imbalance of predicates, so we don't consider the effects of attributes. Attribute annotations can be imported from 'attribute.json', if you require them.

**Comment by Yuqifan1117** [comment]
Thank you for your attention! In our tasks and methods, we address the imbalance of predicates, so we don't consider the effects of attributes and set them to 0. By the way, attribute annotations can be imported from 'attribute.json', if you require them (we also have the expanded VG dataset with attributes).

**Comment by zhangjingxian1998** [comment]
Thank you for answer
